import type {
  AnalysisRun,
  PersonalizedScoredReview,
  PublicScoredReview,
  Restaurant,
  RestaurantPreferenceProfile,
  UserPreferenceProfile,
} from "./types";

const FIXTURE_TIME = "2026-08-25T00:00:00.000Z";

export const DOMAIN_FIXTURE = {
  analysisRun: {
    id: "run-baseline-v2",
    triggerType: "seed",
    status: "succeeded",
    algorithmVersion: "2026-08-25.2",
    modelId: null,
    totalReviews: 3,
    aiCandidateCount: 0,
    aiSuccessCount: 0,
    errorSummary: null,
    startedAt: FIXTURE_TIME,
    finishedAt: "2026-08-25T00:01:00.000Z",
    createdBy: null,
  } satisfies AnalysisRun,
  restaurants: [
    {
      id: "restaurant-balanced-bowl",
      kakaoPlaceId: "synthetic-place-001",
      name: "밸런스 보울 성수",
      categoryGroupCode: "FD6",
      categoryName: "한식",
      roadAddress: "서울 성동구 합성로 1",
      address: "서울 성동구 성수동 합성 1",
      latitude: 37.5445,
      longitude: 127.056,
      region: "성수동",
      createdAt: FIXTURE_TIME,
    },
    {
      id: "restaurant-shellfish-table",
      kakaoPlaceId: "synthetic-place-002",
      name: "조개 테이블 성수",
      categoryGroupCode: "FD6",
      categoryName: "해산물",
      roadAddress: "서울 성동구 합성로 2",
      address: "서울 성동구 성수동 합성 2",
      latitude: 37.545,
      longitude: 127.057,
      region: "성수동",
      createdAt: FIXTURE_TIME,
    },
  ] satisfies readonly Restaurant[],
  publicReviews: [
    {
      review: {
        id: "review-balanced-001",
        externalId: "fixture-review-001",
        restaurantId: "restaurant-balanced-bowl",
        reviewerKey: "synthetic-reviewer-a",
        ratings: { taste: 5, cleanliness: 4, service: 3 },
        reviewText: "고추장 풍미가 분명하고 식기가 깨끗한 합성 리뷰입니다.",
        reviewedAt: "2026-08-20T12:00:00.000Z",
        source: "seed",
        isActive: true,
        createdBy: null,
        createdAt: FIXTURE_TIME,
      },
      feedback: {
        reviewId: "review-balanced-001",
        helpfulCount: 10,
        unhelpfulCount: 0,
        source: "seed",
        updatedAt: FIXTURE_TIME,
      },
      analysis: {
        id: "analysis-balanced-001",
        analysisRunId: "run-baseline-v2",
        reviewId: "review-balanced-001",
        ruleSignals: [],
        ruleScore: 80,
        aiRequired: false,
        aiResult: null,
        aiAdjustment: 0,
        finalTrust: 80,
        explanation: { codes: [], shortExplanation: "공개 감점 신호 없음" },
        createdAt: FIXTURE_TIME,
      },
    },
    {
      review: {
        id: "review-balanced-002",
        externalId: "fixture-review-002",
        restaurantId: "restaurant-balanced-bowl",
        reviewerKey: "synthetic-reviewer-b",
        ratings: { taste: 3, cleanliness: 5, service: 5 },
        reviewText: "응대가 친절하고 매장이 정돈된 합성 리뷰입니다.",
        reviewedAt: "2026-08-21T12:00:00.000Z",
        source: "seed",
        isActive: true,
        createdBy: null,
        createdAt: FIXTURE_TIME,
      },
      feedback: {
        reviewId: "review-balanced-002",
        helpfulCount: 0,
        unhelpfulCount: 10,
        source: "seed",
        updatedAt: FIXTURE_TIME,
      },
      analysis: {
        id: "analysis-balanced-002",
        analysisRunId: "run-baseline-v2",
        reviewId: "review-balanced-002",
        ruleSignals: [],
        ruleScore: 100,
        aiRequired: false,
        aiResult: null,
        aiAdjustment: 0,
        finalTrust: 100,
        explanation: { codes: [], shortExplanation: "공개 감점 신호 없음" },
        createdAt: FIXTURE_TIME,
      },
    },
    {
      review: {
        id: "review-shellfish-001",
        externalId: "fixture-review-003",
        restaurantId: "restaurant-shellfish-table",
        reviewerKey: "synthetic-reviewer-c",
        ratings: { taste: 4.5, cleanliness: 4, service: 4 },
        reviewText: "조개 육수가 진하고 좌석이 편안한 합성 리뷰입니다.",
        reviewedAt: "2026-08-22T12:00:00.000Z",
        source: "seed",
        isActive: true,
        createdBy: null,
        createdAt: FIXTURE_TIME,
      },
      feedback: {
        reviewId: "review-shellfish-001",
        helpfulCount: 2,
        unhelpfulCount: 2,
        source: "seed",
        updatedAt: FIXTURE_TIME,
      },
      analysis: {
        id: "analysis-shellfish-001",
        analysisRunId: "run-baseline-v2",
        reviewId: "review-shellfish-001",
        ruleSignals: [],
        ruleScore: 90,
        aiRequired: false,
        aiResult: null,
        aiAdjustment: 0,
        finalTrust: 90,
        explanation: { codes: [], shortExplanation: "공개 감점 신호 없음" },
        createdAt: FIXTURE_TIME,
      },
    },
  ] satisfies readonly PublicScoredReview[],
  userProfile: {
    profileVersion: "preference-v1",
    axisPreferences: {
      spicy: 80,
      rich: 70,
      cleanliness: 100,
      service: 80,
    },
    excludedFoodTags: ["shellfish"],
    onboardingSources: ["balance_game", "direct_input", "visit_satisfaction"],
    updatedAt: FIXTURE_TIME,
  } satisfies UserPreferenceProfile,
  restaurantProfiles: [
    {
      restaurantId: "restaurant-balanced-bowl",
      axisProfile: {
        spicy: 70,
        sweet: 30,
        light: 50,
        rich: 70,
        value: 75,
        cleanliness: 90,
        service: 70,
      },
      foodTags: ["rice", "beef"],
    },
    {
      restaurantId: "restaurant-shellfish-table",
      axisProfile: {
        spicy: 20,
        sweet: 20,
        light: 65,
        rich: 80,
        value: 55,
        cleanliness: 85,
        service: 80,
      },
      foodTags: ["shellfish", "seafood"],
    },
  ] satisfies readonly RestaurantPreferenceProfile[],
} as const;

export const BALANCED_BOWL_PERSONALIZED_REVIEWS = [
  {
    ...DOMAIN_FIXTURE.publicReviews[0],
    reviewerSimilarityPercent: 100,
  },
  {
    ...DOMAIN_FIXTURE.publicReviews[1],
    reviewerSimilarityPercent: 0,
  },
] satisfies readonly PersonalizedScoredReview[];
